name = "near-ecosystem-explorer"
compatibility_date = "2024-01-08"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "public/build"

[[kv_namespaces]]
binding = "PROJECTS_KV"
id = "5340a26bc58c4072bec0fb5b13f97eaa"
